import type { UnclaimedProperty } from '../types/Property';

export const sampleProperties: UnclaimedProperty[] = [
  {
    id: '189993',
    propertyType: 'AC55: Formerly AC51-53 accounts',
    cashReported: 1250.75,
    sharesReported: 0,
    nameOfSecuritiesReported: '',
    numberOfOwners: '1 of 1',
    ownerName: 'John Smith',
    ownerStreet1: '123 Main St',
    ownerStreet2: '',
    ownerStreet3: '',
    ownerCity: 'Los Angeles',
    ownerState: 'CA',
    ownerZip: '90210',
    ownerCountryCode: 'USA',
    currentCashBalance: 1250.75,
    numberOfPendingClaims: 0,
    numberOfPaidClaims: 0,
    holderName: 'Wells Fargo Bank',
    holderStreet1: '420 Montgomery Street',
    holderStreet2: '',
    holderStreet3: '',
    holderCity: 'San Francisco',
    holderState: 'CA',
    holderZip: '94104',
    cusip: ''
  },
  {
    id: '329848',
    propertyType: '04: Dividends',
    cashReported: 875.00,
    sharesReported: 0,
    nameOfSecuritiesReported: '',
    numberOfOwners: '1 of 1',
    ownerName: 'John A Smith',
    ownerStreet1: '456 Oak Ave',
    ownerStreet2: '',
    ownerStreet3: '',
    ownerCity: 'San Diego',
    ownerState: 'CA',
    ownerZip: '92101',
    ownerCountryCode: 'USA',
    currentCashBalance: 875.00,
    numberOfPendingClaims: 0,
    numberOfPaidClaims: 0,
    holderName: 'Merrill Lynch Pierce Fenner & Smith Inc',
    holderStreet1: 'One Liberty Plaza',
    holderStreet2: '',
    holderStreet3: '',
    holderCity: 'New York',
    holderState: 'NY',
    holderZip: '10006',
    cusip: ''
  },
  {
    id: '330027',
    propertyType: '82: Savings accts/crdt union shrs',
    cashReported: 545.50,
    sharesReported: 0,
    nameOfSecuritiesReported: '',
    numberOfOwners: '1 of 1',
    ownerName: 'Jane Johnson',
    ownerStreet1: '789 Pine Rd',
    ownerStreet2: '',
    ownerStreet3: '',
    ownerCity: 'Sacramento',
    ownerState: 'CA',
    ownerZip: '95814',
    ownerCountryCode: 'USA',
    currentCashBalance: 545.50,
    numberOfPendingClaims: 0,
    numberOfPaidClaims: 0,
    holderName: 'Home Savings & Loan Association',
    holderStreet1: '3731 Wilshire Blvd',
    holderStreet2: '',
    holderStreet3: '',
    holderCity: 'Los Angeles',
    holderState: 'CA',
    holderZip: '90010',
    cusip: ''
  },
  {
    id: '330481',
    propertyType: '76: Other',
    cashReported: 2150.00,
    sharesReported: 0,
    nameOfSecuritiesReported: '',
    numberOfOwners: '1 of 1',
    ownerName: 'Michael Davis',
    ownerStreet1: '321 Elm St',
    ownerStreet2: '',
    ownerStreet3: '',
    ownerCity: 'Oakland',
    ownerState: 'CA',
    ownerZip: '94612',
    ownerCountryCode: 'USA',
    currentCashBalance: 2150.00,
    numberOfPendingClaims: 0,
    numberOfPaidClaims: 0,
    holderName: 'ABC Corporation',
    holderStreet1: '555 Business Blvd',
    holderStreet2: '',
    holderStreet3: '',
    holderCity: 'San Jose',
    holderState: 'CA',
    holderZip: '95113',
    cusip: ''
  },
  {
    id: '567890',
    propertyType: '32: Life insurance',
    cashReported: 5500.25,
    sharesReported: 0,
    nameOfSecuritiesReported: '',
    numberOfOwners: '1 of 1',
    ownerName: 'Sarah Wilson',
    ownerStreet1: '654 Cedar Lane',
    ownerStreet2: '',
    ownerStreet3: '',
    ownerCity: 'Fresno',
    ownerState: 'CA',
    ownerZip: '93701',
    ownerCountryCode: 'USA',
    currentCashBalance: 5500.25,
    numberOfPendingClaims: 0,
    numberOfPaidClaims: 0,
    holderName: 'XYZ Investment Group',
    holderStreet1: '100 Financial Way',
    holderStreet2: '',
    holderStreet3: '',
    holderCity: 'Los Angeles',
    holderState: 'CA',
    holderZip: '90013',
    cusip: ''
  }
]; 